server:
  port: 8001

spring:
  application:
    name: jc-qpp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql 配置
    # url: jdbc:log4jdbc:mysql://127.0.0.1:3306/springweb-demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    # driver-class-name: net.sf.log4jdbc.DriverSpy
    # username: root
    # password: root
    # SQLite 配置
    # url: jdbc:sqlite:user.db
    url: jdbc:sqlite:${app.db.path:/Users/${user.name}/user.db}
    driver-class-name: org.sqlite.JDBC
    druid:
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      validation-query: select 1
  jpa:
    database-platform: com.jc.config.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
service:
  version: 1.0.0